# Generated by Django 4.2.7 on 2024-05-04 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name_plural': 'Contact With D. Niloy'},
        ),
    ]
