# Generated by Django 4.2.7 on 2024-05-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='fee',
            field=models.IntegerField(max_length=10),
        ),
    ]
